### ISSUE TITLE
Publish APK ?

### ISSUE THREAD

**Issue by Ulrar** [rpatel3001/BeaconWear#1]
Hi,

I believe you mentioned you would publish an APK at some point, is that still planned ?
Doesn't look like HA is going to support this any time soon so this app could be handy in the meantime.

Thanks

**Comment by rpatel3001** [comment]
I went ahead and uploaded an APK produced by the repo in its current state. Note that the UI is nonfunctional and the UUID, major and minor numbers, and TX reference power are fixed at compile time. 

https://github.com/rpatel3001/BeaconWear/releases/tag/first_release

**Comment by LostSoulfly** [comment]
> I went ahead and uploaded an APK produced by the repo in its current state. Note that the UI is nonfunctional and the UUID, major and minor numbers, and TX reference power are fixed at compile time.
> 
> https://github.com/rpatel3001/BeaconWear/releases/tag/first_release

Wish I'd seen this at first. Spent an embarrassingly large amount of time wondering why the UI wasn't doing anything, but got it working for me. You saved me a ton of time as I was considering learning Kotlin to create just this sort of thing!

I sincerely hope that HASS integrates this into the app because it will be a massive, at least for me.
